name: flutter_layout_article
description: Flutter layout article.
version: 1.0.1
homepage: https://github.com/marcglasberg/flutter_layout_article
#author: Marcelo Glasberg <marcglasberg@gmail.com>

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

