name: navigate_with_arguments
description: Use Form widget to perform form validation.

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true